schema = 3

[mod]
  [mod."cloud.google.com/go/compute"]
    version = "v1.23.0"
    hash = "sha256-Pd5tMfeatH7p/Mh4b5qUqE9vMDgwwTg6/3Hb8uFZyUw="
  [mod."cloud.google.com/go/compute/metadata"]
    version = "v0.2.3"
    hash = "sha256-kYB1FTQRdTDqCqJzSU/jJYbVUGyxbkASUKbEs36FUyU="
  [mod."github.com/Azure/go-ansiterm"]
    version = "v0.0.0-20210617225240-d185dfc1b5a1"
    hash = "sha256-rOhb0GMLPdnh1302vaxFjO20fM69hCT29hQD1F1YpPg="
  [mod."github.com/GoogleContainerTools/kpt/porch/api"]
    version = "v0.0.0-20230121152246-dc44dbd18a33"
    hash = "sha256-/65qUvJt7mQr7PzJb6btGqV6Dad9pszXU2Pmm710RYE="
  [mod."github.com/GoogleContainerTools/kpt/rollouts"]
    version = "v0.0.0-20230209223911-c6c49d0a0636"
    hash = "sha256-WY3JXn5jG2g5MHgjLQI5i33JNZjPBZh4jBpTaaREOx8="
  [mod."github.com/MakeNowJust/heredoc"]
    version = "v1.0.0"
    hash = "sha256-8hKERAVV1Pew84kc9GkW23dcO8uIUx/+tJQLi+oPwqE="
  [mod."github.com/asaskevich/govalidator"]
    version = "v0.0.0-20230301143203-a9d515a09cc2"
    hash = "sha256-UCENzt1c1tFgsAzK2TNq5s2g0tQMQ5PxFaQKe8hTL/A="
  [mod."github.com/beorn7/perks"]
    version = "v1.0.1"
    hash = "sha256-h75GUqfwJKngCJQVE5Ao5wnO3cfKD9lSIteoLp/3xJ4="
  [mod."github.com/blang/semver/v4"]
    version = "v4.0.0"
    hash = "sha256-dJC22MjnfT5WqJ7x7Tc3Bvpw9tFnBn9HqfWFiM57JVc="
  [mod."github.com/bytecodealliance/wasmtime-go"]
    version = "v0.39.0"
    hash = "sha256-RtWZpY0vulO5VcQDlsXvCsKFdA18+l0erExbWf3Y+9A="
  [mod."github.com/cespare/xxhash/v2"]
    version = "v2.2.0"
    hash = "sha256-nPufwYQfTkyrEkbBrpqM3C2vnMxfIz6tAaBmiUP7vd4="
  [mod."github.com/chai2010/gettext-go"]
    version = "v1.0.2"
    hash = "sha256-dwbhL7uAsAWGfX7Qmfa2hm0YClkbbB7ZHqOiPGP/L18="
  [mod."github.com/containerd/stargz-snapshotter/estargz"]
    version = "v0.14.3"
    hash = "sha256-asLp83pAhaqnJLwIl+QkjNJF1TiV8aetSVmAKc1dDGU="
  [mod."github.com/cpuguy83/go-md2man/v2"]
    version = "v2.0.2"
    hash = "sha256-OvWCtDsVrYzM84SMQwOXPLBxnWnMC1hDm+KiI6zm3uk="
  [mod."github.com/davecgh/go-spew"]
    version = "v1.1.1"
    hash = "sha256-nhzSUrE1fCkN0+RL04N4h8jWmRFPPPWbCuDc7Ss0akI="
  [mod."github.com/docker/cli"]
    version = "v23.0.1+incompatible"
    hash = "sha256-ckbEh+7rLRonJly6uP/iokLdvxhaSs/wrq2vB7CFOHU="
  [mod."github.com/docker/distribution"]
    version = "v2.8.2+incompatible"
    hash = "sha256-ocVWMRt5ErWdVsj3rsNa/QhizG5b/PCu8LoOlUi24/c="
  [mod."github.com/docker/docker"]
    version = "v25.0.6+incompatible"
    hash = "sha256-sUMANzDY4ORfD6qQ25NUhi7PPWF5v8NlOFquiVeDZmc="
  [mod."github.com/docker/docker-credential-helpers"]
    version = "v0.7.0"
    hash = "sha256-Np+esoutU1psMWB0G1ayKwaWVn/XemIXxlVlooXphzg="
  [mod."github.com/emicklei/go-restful/v3"]
    version = "v3.11.0"
    hash = "sha256-Kp5ndPvj1PhK0nscM1pNNK2Q4ahUuLED/baEgL9pKNo="
  [mod."github.com/evanphx/json-patch"]
    version = "v5.6.0+incompatible"
    hash = "sha256-F4hI+H6oWFCKa47+x74M4fqcwDtv3wXOLGVxqDn0F5c="
  [mod."github.com/evanphx/json-patch/v5"]
    version = "v5.6.0"
    hash = "sha256-9P31eky/JuDLlVmKUk4+SfoXWLuJqANm5gSMDzR82No="
  [mod."github.com/exponent-io/jsonpath"]
    version = "v0.0.0-20151013193312-d6023ce2651d"
    hash = "sha256-bAYxtrxx2SFBjO/7UA5h8sgUQrbHTC2OCc8fLXVXf+I="
  [mod."github.com/fatih/camelcase"]
    version = "v1.0.0"
    hash = "sha256-VPzLJ5R6kWzrCwggUOhHlQ3XKW6nCOXxn+0kWZzh+Xw="
  [mod."github.com/fvbommel/sortorder"]
    version = "v1.1.0"
    hash = "sha256-553Rg/amloO6nv67p0ARsKas9QNnTQucpi08vNLtjQU="
  [mod."github.com/go-errors/errors"]
    version = "v1.4.2"
    hash = "sha256-TkRLJlgaVlNxRD9c0ky+CN99tKL4Gx9W06H5a273gPM="
  [mod."github.com/go-logr/logr"]
    version = "v1.2.4"
    hash = "sha256-+FhzmqKsAnsra5p8LuxENXJBHSeuWjQG8Tzhpyd/ps4="
  [mod."github.com/go-openapi/jsonpointer"]
    version = "v0.19.6"
    hash = "sha256-C/ICmPQu0faBiZ/qCHoy6Nzyy2FDO5QiahzlXSCwvIw="
  [mod."github.com/go-openapi/jsonreference"]
    version = "v0.20.2"
    hash = "sha256-klWZKK7LZqSg3HMIrSkjh/NwaZTr+8kTW2ok2+JlioE="
  [mod."github.com/go-openapi/swag"]
    version = "v0.22.3"
    hash = "sha256-iUGFBMt9RobFG+Qsy2zKWEjFARi2xCSCaV2HRDL0vw4="
  [mod."github.com/gogo/protobuf"]
    version = "v1.3.2"
    hash = "sha256-pogILFrrk+cAtb0ulqn9+gRZJ7sGnnLLdtqITvxvG6c="
  [mod."github.com/golang/protobuf"]
    version = "v1.5.3"
    hash = "sha256-svogITcP4orUIsJFjMtp+Uv1+fKJv2Q5Zwf2dMqnpOQ="
  [mod."github.com/google/btree"]
    version = "v1.1.2"
    hash = "sha256-K7V2obq3pLM71Mg0vhhHtZ+gtaubwXPQx3xcIyZDCjM="
  [mod."github.com/google/gnostic-models"]
    version = "v0.6.8"
    hash = "sha256-YzA/XpvPyfdplJtHmAUdQk9P+j0NBwHhW9nj1DaGaoQ="
  [mod."github.com/google/go-cmp"]
    version = "v0.5.9"
    hash = "sha256-lQc4O00R3QSMGs9LP8Sy7A9kj0cqV5rrUdpnGeipIyg="
  [mod."github.com/google/go-containerregistry"]
    version = "v0.14.0"
    hash = "sha256-Jfd7rznW0XY9HvuuIpgx1IfvPqtylfuPgCkGbVW8kTE="
  [mod."github.com/google/gofuzz"]
    version = "v1.2.0"
    hash = "sha256-T6Gz741l45L3F6Dt7fiAuQvQQg59Qtap3zG05M2cfqU="
  [mod."github.com/google/shlex"]
    version = "v0.0.0-20191202100458-e7afc7fbc510"
    hash = "sha256-1f392pCmS7AXVKXIC1SvKlYtK/rvW47F5CCkGT2G6JM="
  [mod."github.com/google/uuid"]
    version = "v1.3.1"
    hash = "sha256-JxAEAB2bFlGPShFreyOWjUahjaGV3xYS5TpfUOikod0="
  [mod."github.com/gregjones/httpcache"]
    version = "v0.0.0-20190611155906-901d90724c79"
    hash = "sha256-AEfenLNBYwZjwHsMG48bpwUyUtjx1BBiK2W5HQruIBc="
  [mod."github.com/igorsobreira/titlecase"]
    version = "v0.0.0-20140109233139-4156b5b858ac"
    hash = "sha256-NAcKTGofVv0kFPSuGHNJKZ9++AADHt/Zogpl7SIDOdE="
  [mod."github.com/imdario/mergo"]
    version = "v0.3.13"
    hash = "sha256-03LKAZXgR5YUMeK5IRh2ds2GyV6uSbdq5QCPbAzlTus="
  [mod."github.com/inconshreveable/mousetrap"]
    version = "v1.1.0"
    hash = "sha256-XWlYH0c8IcxAwQTnIi6WYqq44nOKUylSWxWO/vi+8pE="
  [mod."github.com/jedib0t/go-pretty/v6"]
    version = "v6.4.4"
    hash = "sha256-aLgJ9r4eM6gPspccS5UMHJa8Gr7thwJR8bvnZXiUn9E="
  [mod."github.com/jonboulle/clockwork"]
    version = "v0.2.2"
    hash = "sha256-ryvMsRMd1CeuYyyLTfGRWb36AbZyxtomPBEB7hzrrqE="
  [mod."github.com/josharian/intern"]
    version = "v1.0.0"
    hash = "sha256-LJR0QE2vOQ2/2shBbO5Yl8cVPq+NFrE3ers0vu9FRP0="
  [mod."github.com/json-iterator/go"]
    version = "v1.1.12"
    hash = "sha256-To8A0h+lbfZ/6zM+2PpRpY3+L6725OPC66lffq6fUoM="
  [mod."github.com/klauspost/compress"]
    version = "v1.16.0"
    hash = "sha256-bMMwJhgK/uR3xq16XdqE2ge8x0fn6WK1NGkU3cKSWV4="
  [mod."github.com/liggitt/tabwriter"]
    version = "v0.0.0-20181228230101-89fcab3d43de"
    hash = "sha256-b6pLitORwgfGpOHpe45ykj00P17utbDv8bv6MCVoCBM="
  [mod."github.com/mailru/easyjson"]
    version = "v0.7.7"
    hash = "sha256-NVCz8MURpxgOjHXqxOZExqV4bnpHggpeAOyZDArjcy4="
  [mod."github.com/mattn/go-runewidth"]
    version = "v0.0.13"
    hash = "sha256-93AwJFA8B2pwNJAPe64yN0c/CwkJNGFDWFe/HpzDVuk="
  [mod."github.com/matttproud/golang_protobuf_extensions"]
    version = "v1.0.4"
    hash = "sha256-uovu7OycdeZ2oYQ7FhVxLey5ZX3T0FzShaRldndyGvc="
  [mod."github.com/mitchellh/go-homedir"]
    version = "v1.1.0"
    hash = "sha256-oduBKXHAQG8X6aqLEpqZHs5DOKe84u6WkBwi4W6cv3k="
  [mod."github.com/mitchellh/go-wordwrap"]
    version = "v1.0.1"
    hash = "sha256-fiD7kh5037BjA0vW6A2El0XArkK+4S5iTBjJB43BNYo="
  [mod."github.com/moby/spdystream"]
    version = "v0.2.0"
    hash = "sha256-Feme5UoWuBCvnLPKw1ozKkF3SM7PAjjPFQZ3TJhghR0="
  [mod."github.com/moby/term"]
    version = "v0.0.0-20221205130635-1aeaba878587"
    hash = "sha256-wX2ftzjEHzltzN68CsYVXMiaLPNU7V2phVyyPKv3mn8="
  [mod."github.com/modern-go/concurrent"]
    version = "v0.0.0-20180306012644-bacd9c7ef1dd"
    hash = "sha256-OTySieAgPWR4oJnlohaFTeK1tRaVp/b0d1rYY8xKMzo="
  [mod."github.com/modern-go/reflect2"]
    version = "v1.0.2"
    hash = "sha256-+W9EIW7okXIXjWEgOaMh58eLvBZ7OshW2EhaIpNLSBU="
  [mod."github.com/monochromegane/go-gitignore"]
    version = "v0.0.0-20200626010858-205db1a8cc00"
    hash = "sha256-j1Mgb2TUUIiBcXB+slOkjtvcjmqSMEsG5RZYE7vGXOU="
  [mod."github.com/munnerz/goautoneg"]
    version = "v0.0.0-20191010083416-a7dc8b61c822"
    hash = "sha256-79URDDFenmGc9JZu+5AXHToMrtTREHb3BC84b/gym9Q="
  [mod."github.com/onsi/gomega"]
    version = "v1.27.10"
    hash = "sha256-sBWpNFXShK1qsJjsHIHkZLQRjWG6k9QLATooSamZxPQ="
  [mod."github.com/opencontainers/go-digest"]
    version = "v1.0.0"
    hash = "sha256-cfVDjHyWItmUGZ2dzQhCHgmOmou8v7N+itDkLZVkqkQ="
  [mod."github.com/opencontainers/image-spec"]
    version = "v1.1.0-rc2"
    hash = "sha256-833S8D86IumLRpfrKBzpZCtLsTEnGBWbI3dTYd6BdFg="
  [mod."github.com/otiai10/copy"]
    version = "v1.7.0"
    hash = "sha256-hnSIo6tNLhxXVE8WGfivIhnuwxvQYAg7oa1b6TNpTsc="
  [mod."github.com/peterbourgon/diskv"]
    version = "v2.0.1+incompatible"
    hash = "sha256-K4mEVjH0eyxyYHQRxdbmgJT0AJrfucUwGB2BplRRt9c="
  [mod."github.com/philopon/go-toposort"]
    version = "v0.0.0-20170620085441-9be86dbd762f"
    hash = "sha256-3YCuJcI3egWlm+Zg3eao2URcQIQEK9UibmHzBtpQzj0="
  [mod."github.com/pkg/errors"]
    version = "v0.9.1"
    hash = "sha256-mNfQtcrQmu3sNg/7IwiieKWOgFQOVVe2yXgKBpe/wZw="
  [mod."github.com/pmezard/go-difflib"]
    version = "v1.0.0"
    hash = "sha256-/FtmHnaGjdvEIKAJtrUfEhV7EVo5A/eYrtdnUkuxLDA="
  [mod."github.com/prep/wasmexec"]
    version = "v0.0.0-20220807105708-6554945c1dec"
    hash = "sha256-gVEknKQZdPo9/FKe/5zyOeYSCDv52AnBHQgED6QYSFo="
  [mod."github.com/prometheus/client_golang"]
    version = "v1.16.0"
    hash = "sha256-P/b4/8m1ztF0fCLSJ+eRXN74Bncx2vjOJx7nFl2QEg4="
  [mod."github.com/prometheus/client_model"]
    version = "v0.4.0"
    hash = "sha256-4P0sPWpxa69gGM6zm3dA06cH6twaeopq22VVDJjucHA="
  [mod."github.com/prometheus/common"]
    version = "v0.44.0"
    hash = "sha256-8n3gSWKDSJtGfOQgxsiCGyTnUjb5hvSxJi/hPcrE5Oo="
  [mod."github.com/prometheus/procfs"]
    version = "v0.10.1"
    hash = "sha256-EJ8q8wux4964WE4X7UkHb+MXjLhX4TROJaoLIQvD/eQ="
  [mod."github.com/rivo/uniseg"]
    version = "v0.2.0"
    hash = "sha256-GLj0jiGrT03Ept4V6FXCN1yeZ/b6PpS3MEXK6rYQ8Eg="
  [mod."github.com/russross/blackfriday/v2"]
    version = "v2.1.0"
    hash = "sha256-R+84l1si8az5yDqd5CYcFrTyNZ1eSYlpXKq6nFt4OTQ="
  [mod."github.com/sergi/go-diff"]
    version = "v1.2.0"
    hash = "sha256-d2higuBRee4ylRuCpPQV5+g0XK5yNQgDpudNor0qD2o="
  [mod."github.com/sirupsen/logrus"]
    version = "v1.9.0"
    hash = "sha256-xOwGFsYGIxNiurS8Zue8mhlFK/G7U1LVFFrv4vcr1GM="
  [mod."github.com/spf13/cobra"]
    version = "v1.7.0"
    hash = "sha256-bom9Zpnz8XPwx9IVF+GAodd3NVQ1dM1Uwxn8sy4Gmzs="
  [mod."github.com/spf13/pflag"]
    version = "v1.0.5"
    hash = "sha256-w9LLYzxxP74WHT4ouBspH/iQZXjuAh2WQCHsuvyEjAw="
  [mod."github.com/spyzhov/ajson"]
    version = "v0.9.0"
    hash = "sha256-TVJiU5FB0b57ykYvwviYNaIatQnudcrsKqgolQBjn9U="
  [mod."github.com/stretchr/testify"]
    version = "v1.8.4"
    hash = "sha256-MoOmRzbz9QgiJ+OOBo5h5/LbilhJfRUryvzHJmXAWjo="
  [mod."github.com/vbatts/tar-split"]
    version = "v0.11.2"
    hash = "sha256-0MhEqt6dl2pMudEcrixaT8w1R4Ovwaiz7MuHBN2zKOM="
  [mod."github.com/xlab/treeprint"]
    version = "v1.2.0"
    hash = "sha256-g85HyWGLZuD/TFXZzmXT+u9TA1xIT5escUVhnofsYQI="
  [mod."go.starlark.net"]
    version = "v0.0.0-20230525235612-a134d8f9ddca"
    hash = "sha256-lO0g2HMFn+ulv5r08coGIaxMdi5mTp1YNzl9nDraSjs="
  [mod."golang.org/x/mod"]
    version = "v0.10.0"
    hash = "sha256-g0T2wz+K0nhPWdVQJRGGqEqzlTHMBahv+9C3y090eIM="
  [mod."golang.org/x/net"]
    version = "v0.17.0"
    hash = "sha256-qRawHWLSsJ06QNbLhUWPXGVSO1eaioeC9xZlUEWN8J8="
  [mod."golang.org/x/oauth2"]
    version = "v0.8.0"
    hash = "sha256-Ge6x2dR+ap7JSF9W1FwaSCK9ilyuGTQWpgFQHg83Sho="
  [mod."golang.org/x/sync"]
    version = "v0.2.0"
    hash = "sha256-hKk9zsy2aXY7R0qGFZhGOVvk5qD17f6KHEuK4rGpTsg="
  [mod."golang.org/x/sys"]
    version = "v0.13.0"
    hash = "sha256-/+RDZ0a0oEfJ0k304VqpJpdrl2ZXa3yFlOxy4mjW7w0="
  [mod."golang.org/x/term"]
    version = "v0.13.0"
    hash = "sha256-sLN+cjSZN2tfg/Lm9Ae4vYzoXREclMumxfksYFokymQ="
  [mod."golang.org/x/text"]
    version = "v0.14.0"
    hash = "sha256-yh3B0tom1RfzQBf1RNmfdNWF1PtiqxV41jW1GVS6JAg="
  [mod."golang.org/x/time"]
    version = "v0.3.0"
    hash = "sha256-/hmc9skIswMYbivxNS7R8A6vCTUF9k2/7tr/ACkcEaM="
  [mod."google.golang.org/appengine"]
    version = "v1.6.7"
    hash = "sha256-zIxGRHiq4QBvRqkrhMGMGCaVL4iM4TtlYpAi/hrivS4="
  [mod."google.golang.org/protobuf"]
    version = "v1.31.0"
    hash = "sha256-UdIk+xRaMfdhVICvKRk1THe3R1VU+lWD8hqoW/y8jT0="
  [mod."gopkg.in/evanphx/json-patch.v5"]
    version = "v5.6.0"
    hash = "sha256-F4hI+H6oWFCKa47+x74M4fqcwDtv3wXOLGVxqDn0F5c="
  [mod."gopkg.in/inf.v0"]
    version = "v0.9.1"
    hash = "sha256-z84XlyeWLcoYOvWLxPkPFgLkpjyb2Y4pdeGMyySOZQI="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.4.0"
    hash = "sha256-uVEGglIedjOIGZzHW4YwN1VoRSTK8o0eGZqzd+TNdd0="
  [mod."gopkg.in/yaml.v3"]
    version = "v3.0.1"
    hash = "sha256-FqL9TKYJ0XkNwJFnq9j0VvJ5ZUU1RvH/52h/f5bkYAU="
  [mod."gotest.tools"]
    version = "v2.2.0+incompatible"
    hash = "sha256-BYTGCeD1GH0nUMxaP1ARTpfGk3vQroDNAgb3LYKhon4="
  [mod."k8s.io/api"]
    version = "v0.28.4"
    hash = "sha256-JErtAtdt52ppZMlt2MxmCFWDJgQu5l3urWMkSfnwWTM="
  [mod."k8s.io/apiextensions-apiserver"]
    version = "v0.28.4"
    hash = "sha256-/KaUznpsDjal8wkxPw0YPyJK+AMBi3dndhso6V7LN4w="
  [mod."k8s.io/apimachinery"]
    version = "v0.28.4"
    hash = "sha256-BPpMeP1vhLhi4s+nIKwiuuOgJRzxpoB4lchWXTsbq7I="
  [mod."k8s.io/cli-runtime"]
    version = "v0.28.4"
    hash = "sha256-bKkk/mpr5alAqoYM3on8yz03Lg7rq4xORFg1mGfK+1k="
  [mod."k8s.io/client-go"]
    version = "v0.28.4"
    hash = "sha256-Jl0JhT20DjjlP93RHNp+Wlzexl0dvY7YPaahLoOPnMs="
  [mod."k8s.io/component-base"]
    version = "v0.28.4"
    hash = "sha256-khxEASMreyE9Ek9T961MdKsFvBuKQC0fTeIh16ZRYjs="
  [mod."k8s.io/klog/v2"]
    version = "v2.100.1"
    hash = "sha256-0pf6/CrK6R6FjlKYjy9ybL3+KaAMNEaWUf0mUs6F5+c="
  [mod."k8s.io/kube-openapi"]
    version = "v0.0.0-20230717233707-2695361300d9"
    hash = "sha256-3d/G/oRLbgBlFFzX8DBd5nQc0EE81rZ9xtHhrQrdA04="
  [mod."k8s.io/kubectl"]
    version = "v0.28.4"
    hash = "sha256-l4t77Wd9vHf/qqwDkVsNLJE9brlxELpnoMr/+vwbREg="
  [mod."k8s.io/utils"]
    version = "v0.0.0-20230726121419-3b25d923346b"
    hash = "sha256-r8VhhAYGPouGGgXu02ymVwF6k+WmBc4ij0qynPRtXEE="
  [mod."sigs.k8s.io/cli-utils"]
    version = "v0.36.0"
    hash = "sha256-eRBpzMuwGZhfzDVKepZ6Goapsq7Hd+zxHC68p18NPsY="
  [mod."sigs.k8s.io/controller-runtime"]
    version = "v0.16.3"
    hash = "sha256-3VvW9CZrXJ7krBGsYk3MJMATtrfVuhO5xVyKQ17Az2c="
  [mod."sigs.k8s.io/json"]
    version = "v0.0.0-20221116044647-bc3834ca7abd"
    hash = "sha256-XDBMN2o450IHiAwEpBVsvo9e7tYZa+EXWrifUNTdNMU="
  [mod."sigs.k8s.io/kustomize/api"]
    version = "v0.15.0"
    hash = "sha256-6qNHYI+imRqlTxwMTowLxruDnEAHX5EDjiPZqeHTgnE="
  [mod."sigs.k8s.io/kustomize/kyaml"]
    version = "v0.15.0"
    hash = "sha256-Sq6K9YCho8/h5N6hTgChhDFrbjFQeD5VYUZa86GCG6g="
  [mod."sigs.k8s.io/structured-merge-diff/v4"]
    version = "v4.2.3"
    hash = "sha256-v6u6ZqnrEeQ2c7BYkltPKuBFL7+939OT1EbWw0mUE7U="
  [mod."sigs.k8s.io/yaml"]
    version = "v1.4.0"
    hash = "sha256-Hd/M0vIfIVobDd87eb58p1HyVOjYWNlGq2bRXfmtVno="
