name: Check gomod2nix
on:
  push:

  pull_request_target:

jobs:
  check-gomod2nix:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v24
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Check gomod2nix.toml is up to date
        run: |-
          nix run .#gomod2nix
          git diff --exit gomod2nix.toml
