name: Update gomod2nix
on:
  issue_comment:
    types: [created]

jobs:
  update-gomod2nix:
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/gomod2nix' }}
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v24
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Checkout PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr checkout ${{ github.event.issue.number }}

      - name: Update gomod2nix.toml
        run: |-
          nix run .#gomod2nix

          git add gomod2nix.toml

          git commit -m "update gomod2nix.toml"

          git push
